// Generated by _shared/build.py: Cloudflare Pages guard. Serves only live Cloudflare creators
// (minus their notes) plus shared assets, whatever the dashboard build settings are, so the
// research notes, content.json and repo files are never public even if the repo root is deployed.
const ALLOW = ["/assets/", "/gocholive/", "/havemercitrades/", "/mightystocks/", "/thaflipking/"];
const PRIVATE = new Set(["dossier.md", "offer-deck-filled.md", "README.md", "content.json"]);

export async function onRequest(ctx) {
  let path;
  try { path = decodeURIComponent(new URL(ctx.request.url).pathname); } catch { return notFound(ctx); }
  const parts = path.split("/");
  const allowed = path === "/404" || path === "/404.html" || ALLOW.some(a => path === a.slice(0, -1) || path.startsWith(a));
  if (!allowed || PRIVATE.has(parts[parts.length - 1]) || parts.some(x => x.startsWith(".") || x.startsWith("_"))) return notFound(ctx);
  return ctx.next();
}

async function notFound(ctx) {
  const page = await ctx.env.ASSETS.fetch(new URL("/404.html", ctx.request.url), { redirect: "follow" });
  return new Response(page.ok ? page.body : "Not found", {
    status: 404,
    headers: { "content-type": "text/html; charset=utf-8", "x-robots-tag": "noindex, nofollow" },
  });
}
