// Generated by _shared/build.py: Cloudflare Pages guard. Serves only live Cloudflare creators
// (minus their notes) plus shared assets, whatever the dashboard build settings are, so the
// research notes, content.json and repo files are never public even if the repo root is deployed.
//
// Visit alerts: when a real person opens a pitch page or one of its deliverables, a push goes to
// ntfy (https://ntfy.sh). The topic is a secret set in Cloudflare (Pages → Settings → Variables and
// Secrets → NTFY_TOPIC), never in this public repo; without it nothing is sent. NTFY_TOKEN (an ntfy account
// access token, also a secret) is needed in practice: anonymous ntfy.sh limits per IP, and Cloudflare's
// shared egress IPs hit that daily quota (429) before any visitor arrives. Link-preview bots,
// prefetches and the owner's own devices (opened once with ?me=1, which sets a cookie) are skipped.
const ALLOW = ["/assets/", "/gocholive/", "/havemercitrades/", "/mightystocks/", "/thaflipking/"];
const PRIVATE = new Set(["dossier.md", "offer-deck-filled.md", "README.md", "content.json"]);
const CREATORS = {"gocholive": {"name": "Franklin Ovalles", "instagram": "gocholive"}, "havemercitrades": {"name": "Mercedith (Merci)", "instagram": "havemercitrades"}, "mightystocks": {"name": "Marcelo Estrada", "instagram": "mightystocks"}, "thaflipking": {"name": "Donyell Green", "instagram": "thaflipking"}};
const PAGES = { "": "pitch page", "funnel/": "funnel page", "funnel/thank-you/": "booking page", "emails/": "email sequence", "ads/": "ad scripts" };
const BOTS = /bot|crawl|spider|slurp|preview|facebookexternalhit|facebot|whatsapp|telegram|slack|discord|skype|linkedin|pinterest|embedly|quora|vkshare|google(?:-|image|other|web)|feedfetcher|mediapartners|headless|playwright|puppeteer|lighthouse|pingdom|uptime|monitor|curl|wget|python|node-fetch|undici|axios|go-http|java\/|okhttp|http-client|scrapy|cloudflare/i;

export async function onRequest(ctx) {
  let url, path;
  try { url = new URL(ctx.request.url); path = decodeURIComponent(url.pathname); } catch { return notFound(ctx); }
  const parts = path.split("/");
  const allowed = path === "/404" || path === "/404.html" || ALLOW.some(a => path === a.slice(0, -1) || path.startsWith(a));
  if (!allowed || PRIVATE.has(parts[parts.length - 1]) || parts.some(x => x.startsWith(".") || x.startsWith("_"))) return notFound(ctx);
  const res = await ctx.next();
  // Self-test: ?alerttest=<the secret topic> sends one alert and reports ntfy's answer in x-alert-result.
  const at = url.searchParams.get("alerttest");
  if (at && at.trim() === topicOf(ctx)) {
    let result;
    try { const r = await sendAlert(ctx, { topic: topicOf(ctx), title: "Alert self-test", message: "The visit alert on infooperate.pages.dev works.", tags: ["white_check_mark"] }); result = `ntfy ${r.status} ${(await r.text()).slice(0, 120)}`; }
    catch (e) { result = `error ${e && e.message}`; }
    const r = new Response(res.body, res);
    r.headers.set("x-alert-result", result.split("\n").join(" ").split("\r").join(" "));
    return r;
  }
  // Diagnostics without revealing secrets: ?alertdiag=1 → which settings exist, their length and a SHA-256 fingerprint.
  if (url.searchParams.get("alertdiag") === "1") {
    const fp = async v => { const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(v)); return [...new Uint8Array(d)].slice(0, 4).map(x => x.toString(16).padStart(2, "0")).join(""); };
    const t = topicOf(ctx), k = ((ctx.env && ctx.env.NTFY_TOKEN) || "").trim();
    const r = new Response(res.body, res);
    r.headers.set("x-alert-diag", `topic:${t ? "set" : "missing"} len=${t.length} fp=${t ? await fp(t) : "-"}; token:${k ? "set" : "missing"} len=${k.length} tk_=${k.startsWith("tk_")}`);
    return r;
  }
  if (url.searchParams.get("me") === "1") {
    const r = new Response(res.body, res);
    r.headers.append("set-cookie", "io_me=1; Path=/; Max-Age=31536000; Secure; SameSite=Lax");
    return r;
  }
  try { maybeNotify(ctx, url, path, res.status); } catch (e) {}
  return res;
}

function maybeNotify(ctx, url, path, status) {
  const topic = topicOf(ctx);
  if (!topic || status !== 200 || ctx.request.method !== "GET") return;
  const m = path.match(/^\/([a-z0-9-]+)\/(.*)$/);
  if (!m || !CREATORS[m[1]] || !(m[2] in PAGES)) return;
  const h = ctx.request.headers, ua = h.get("user-agent") || "";
  if (!ua || BOTS.test(ua)) return;
  if (/(^|;\s*)io_me=1/.test(h.get("cookie") || "")) return;
  const purpose = (h.get("sec-purpose") || h.get("purpose") || h.get("x-moz") || "").toLowerCase();
  if (purpose.includes("prefetch") || purpose.includes("prerender")) return;
  const c = CREATORS[m[1]], cf = ctx.request.cf || {};
  const where = [cf.city, cf.country].filter(Boolean).join(", ") || "unknown location";
  const device = /iphone/i.test(ua) ? "iPhone" : /ipad/i.test(ua) ? "iPad" : /android/i.test(ua) ? "Android" : /macintosh/i.test(ua) ? "Mac" : /windows/i.test(ua) ? "Windows" : "other device";
  const app = /instagram/i.test(ua) ? " (Instagram app)" : /fban|fbav/i.test(ua) ? " (Facebook app)" : /gsa\//i.test(ua) ? " (Google app)" : "";
  let via = "direct / email";
  try { const ref = h.get("referer"); if (ref) { const rh = new URL(ref).hostname.replace(/^www\./, ""); via = rh === url.hostname ? "their own click on the page" : rh; } } catch (e) {}
  const msg = {
    topic,
    title: `${c.name} opened the ${PAGES[m[2]]}`,
    message: `${m[1]} · ${where} · ${device}${app} · via ${via}`,
    tags: [m[2] === "" ? "eyes" : "point_right"],
    priority: m[2] === "" ? 4 : 3,
    click: c.instagram ? `https://www.instagram.com/${c.instagram}/` : url.origin + "/" + m[1] + "/",
  };
  ctx.waitUntil(sendAlert(ctx, msg).catch(() => {}));
}

// Secrets pasted into the dashboard often carry a stray space or newline; ignore it.
function topicOf(ctx) { return ((ctx.env && ctx.env.NTFY_TOPIC) || "").trim(); }

function sendAlert(ctx, msg) {
  return fetch((ctx.env.NTFY_SERVER || "https://ntfy.sh").replace(/\/$/, "") + "/", {
    method: "POST", body: JSON.stringify(msg),
    headers: Object.assign({ "content-type": "application/json", "user-agent": "infooperate-visit-alert" },
      (ctx.env.NTFY_TOKEN || "").trim() ? { authorization: "Bearer " + ctx.env.NTFY_TOKEN.trim() } : {}),
  });
}

async function notFound(ctx) {
  const page = await ctx.env.ASSETS.fetch(new URL("/404.html", ctx.request.url), { redirect: "follow" });
  return new Response(page.ok ? page.body : "Not found", {
    status: 404,
    headers: { "content-type": "text/html; charset=utf-8", "x-robots-tag": "noindex, nofollow" },
  });
}
